---
name: Build and Test Android App
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk

      - name: Install Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$HOME/android-sdk/cmdline-tools/tools/bin
          echo "y" | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Build and test
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
