---
name: Build and Test Android App
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d "$HOME/android-sdk/cmdline-tools"
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$HOME/android-sdk/cmdline-tools/tools/bin
          yes | sdkmanager --licenses

          # Install necessary SDK components
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.0"

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Build and test
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
